const { PrismaClient } = require("@prisma/client")

const prisma = new PrismaClient();

async function main() {
  const vozila = [
    {
      id: "1b2a3c4d-5e6f-7g8h-9i0j-k1l2m3n4o5p6",
      slika: "https://example.com/vehicle1.jpg",
      marka: "BMW",
      model: "X5",
      karoserija: "SUV",
      godiste: 2022,
      gorivo: "Dizel",
      kubikaza: 2993,
      snagaMotora: "210kW",
      cena: 75000.0,
      spoljasnjaBoja: "Crna",
      unutrasnjaBoja: "Bež",
      brSedista: 5,
      brVrata: 5,
      zemljaUvoza: "Nemačka",
      description: "Odlično očuvan, kao nov, uvoz iz Nemačke.",
    },
    {
      id: "1b2c3d4e-5f6g-7h8i-9j0k-l1m2n3o4p5q6",
      slika: "https://example.com/vehicle2.jpg",
      marka: "Audi",
      model: "A6",
      karoserija: "Limuzina",
      godiste: 2020,
      gorivo: "Benzin",
      kubikaza: 1984,
      snagaMotora: "140kW",
      cena: 55000.0,
      spoljasnjaBoja: "Siva",
      unutrasnjaBoja: "Crna",
      brSedista: 5,
      brVrata: 4,
      zemljaUvoza: "Austrija",
      description: "Elegantna limuzina, idealna za poslovne ljude.",
    },
    {
      id: "1c2d3e4f-5g6h-7i8j-9k0l-m1n2o3p4q5r6",
      slika: "https://example.com/vehicle3.jpg",
      marka: "Mercedes-Benz",
      model: "C-Class",
      karoserija: "Kupe",
      godiste: 2021,
      gorivo: "Hibrid",
      kubikaza: 1991,
      snagaMotora: "190kW",
      cena: 65000.0,
      spoljasnjaBoja: "Bela",
      unutrasnjaBoja: "Crvena",
      brSedista: 4,
      brVrata: 2,
      zemljaUvoza: "Švajcarska",
      description: "Sportski kupe sa modernim tehnologijama.",
    },
    {
      id: "2a3b4c5d-6e7f-8g9h-0i1j-k2l3m4n5o6p7",
      slika: "https://example.com/vehicle4.jpg",
      marka: "Volkswagen",
      model: "Golf",
      karoserija: "Hečbek",
      godiste: 2019,
      gorivo: "Dizel",
      kubikaza: 1968,
      snagaMotora: "110kW",
      cena: 25000.0,
      spoljasnjaBoja: "Plava",
      unutrasnjaBoja: "Siva",
      brSedista: 5,
      brVrata: 5,
      zemljaUvoza: "Slovenija",
      description: "Pouzdan gradski automobil, ekonomičan za vožnju.",
    },
    {
      id: "3c4d5e6f-7g8h-9i0j-k1l2-m3n4o5p6q7r8",
      slika: "https://example.com/vehicle5.jpg",
      marka: "Toyota",
      model: "RAV4",
      karoserija: "SUV",
      godiste: 2023,
      gorivo: "Hibrid",
      kubikaza: 2487,
      snagaMotora: "160kW",
      cena: 40000.0,
      spoljasnjaBoja: "Srebrna",
      unutrasnjaBoja: "Crna",
      brSedista: 5,
      brVrata: 5,
      zemljaUvoza: "Italija",
      description: "Moderan SUV idealan za porodice.",
    },
    {
      id: "4d5e6f7g-8h9i-0j1k-2l3m-n4o5p6q7r8s9",
      slika: "https://example.com/vehicle6.jpg",
      marka: "Ford",
      model: "Focus",
      karoserija: "Karavan",
      godiste: 2018,
      gorivo: "Dizel",
      kubikaza: 1499,
      snagaMotora: "88kW",
      cena: 15000.0,
      spoljasnjaBoja: "Bela",
      unutrasnjaBoja: "Crna",
      brSedista: 5,
      brVrata: 5,
      zemljaUvoza: "Francuska",
      description: "Savršeno očuvan karavan sa velikim gepekom.",
    },
    {
      id: "5e6f7g8h-9i0j-1k2l-3m4n-o5p6q7r8s9t0",
      slika: "https://example.com/vehicle7.jpg",
      marka: "Skoda",
      model: "Octavia",
      karoserija: "Limuzina",
      godiste: 2020,
      gorivo: "Metan",
      kubikaza: 1395,
      snagaMotora: "96kW",
      cena: 18000.0,
      spoljasnjaBoja: "Zelena",
      unutrasnjaBoja: "Crna",
      brSedista: 5,
      brVrata: 4,
      zemljaUvoza: "Češka",
      description: "Ekonomičan automobil na metan, odlično stanje.",
    },
    {
      id: "6f7g8h9i-0j1k-2l3m-4n5o-6p7q8r9s0t1u2",
      slika: "https://example.com/vehicle8.jpg",
      marka: "Honda",
      model: "Civic",
      karoserija: "Hečbek",
      godiste: 2017,
      gorivo: "Benzin",
      kubikaza: 1595,
      snagaMotora: "92kW",
      cena: 12000.0,
      spoljasnjaBoja: "Crvena",
      unutrasnjaBoja: "Crna",
      brSedista: 5,
      brVrata: 5,
      zemljaUvoza: "Belgija",
      description: "Dinamičan i pouzdan gradski automobil.",
    },
    {
      id: "7g8h9i0j-1k2l-3m4n-5o6p-7q8r9s0t1u2v3",
      slika: "https://example.com/vehicle9.jpg",
      marka: "Hyundai",
      model: "Tucson",
      karoserija: "SUV",
      godiste: 2021,
      gorivo: "Benzin",
      kubikaza: 1998,
      snagaMotora: "132kW",
      cena: 31000.0,
      spoljasnjaBoja: "Narandžasta",
      unutrasnjaBoja: "Crna",
      brSedista: 5,
      brVrata: 5,
      zemljaUvoza: "Mađarska",
      description: "Prostran SUV sa naprednim funkcijama.",
    },
    {
      id: "8h9i0j1k-2l3m-4n5o-6p7q-8r9s0t1u2v3w4",
      slika: "https://example.com/vehicle10.jpg",
      marka: "Kia",
      model: "Sportage",
      karoserija: "SUV",
      godiste: 2022,
      gorivo: "Hibrid",
      kubikaza: 1598,
      snagaMotora: "130kW",
      cena: 35000.0,
      spoljasnjaBoja: "Zlatna",
      unutrasnjaBoja: "Smeđa",
      brSedista: 5,
      brVrata: 5,
      zemljaUvoza: "Poljska",
      description: "Odličan SUV sa vrhunskom opremom.",
    },
  ];
  await prisma.proizvod.createMany({
    data: vozila
  });
  // await prisma.listaZelja.createMany({
  //     data: [
  //       {
  //         korisnik_id: '795fe79b-b0fe-4849-b093-aed12b7c377a',
  //         proizvod_id: '3befc5e4-84af-42e9-88b4-2ad15fc7bfb9',
  //       },
  //       {
  //         korisnik_id: '795fe79b-b0fe-4849-b093-aed12b7c377a',
  //         proizvod_id: 'ca231363-d05e-45ff-8eb3-b13b39128353',
  //       }
  //     ]
  // });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });